### ISSUE TITLE
几个使用问题

### ISSUE THREAD

**Issue by In2013** [xiaoqiangjun/gugubot#1]
1.使用该账号注册新浪邮箱，微博绑定的是`xxxx@qq.com`这样的邮箱，注册新浪邮箱时遇到问题，提示`纯数字不能注册`，如果用绑定的手机号注册`手机新浪邮箱`如`12345@sina.cn`应该是不能登录的，和微博号没有绑定，这样的话改成直接填写`微博cookies`登录是不是更合适呢
2.如果已经重复登录直到无需扫码登录，还需要填写`ocr_token = ""  # orc密钥，在fast.95man.com申请`吗
3.`weibo.py` 尾部末尾添加账号尚不明确

**Comment by In2013** [comment]
@xiaoqiangjun

**Comment by xiaoqiangjun** [comment]
抱歉才看到你的问题。
1. 微博账号绑定手机号，然后用手机号注册新浪邮箱，可以直接注册手机邮箱。总之要的结果是，在[邮箱界面](https://mail.sina.com.cn/)成功登录之后，点击页脚的[邮箱官方微博]()链接能够跳转微博。关于用微博cookies直接登录，因为考虑到cookies会过期，需要人工更新，和我的需求不太符合，所以就没有考虑，你可以fork之后尝试一下。
2. 这里的ocr密钥是用来做图形验证码的，在你登录过程中如果不再需要输入图片的验证码时，可以留空。
3. 你是说使用如何填写参数让它运行吗？你可以在161行`weibo = Weibo()`的括号里填写你的信息，具体的参数信息如果你的ide没有提示，可以看23行初始化函数的注释。

**Comment by In2013** [comment]
感谢大佬回复！
1.用手机号注册时提示手机号已经绑定账户`*****@qq.com`无法注册，于是我尝试找回`手机号码@sina.cn`这个邮箱的密码，这邮箱其实是没有注册过的，但确实作为账户和微博关联了，似乎是被系统预留了，找回密码后登录上去，还是我原来的微博，此时用`手机号码@sina.cn`和`*****@qq.com`这两个邮箱都可以登录我的微博，但是用手机号和`手机号码@sina.cn`在邮箱界面登录是进不去邮箱的，直接跳转到微博，如此即便手机邮箱不能正常使用（或者实际上没注册上），也可以达到登录微博的目的？好吧。
2.重复登录直到无需扫码登录，可能有点玄，多次登录都要输入手机验证码或扫码，像宽带ip经常变的会不会太容易歇菜了，不知道渣浪是检测什么东西才不需要验证码的

**Comment by xiaoqiangjun** [comment]
1.再确认下，这里说的登录界面，是新浪邮箱的界面，mail.sina.com.cn，在这里登录邮箱，之后再登录成功界面的底部，有一个“邮箱官方微博”，确定从这里点进去会成功登录你想要的微博账号。2.如果是在新浪微博登录的话，会一直需要验证的，这里说的还是邮箱的界面，在mail.sina.com.cn这里，多扫码或者短信登录几次，就可以不用验证来登录了。
我readme写的确实有点不够清晰哈，有时间我更新一下，加几张图就比较好理解了，其实重点就是微博的安全防护做的更高，邮箱登录就像是一个漏洞一样，以前漏洞不止邮箱一个，但是几个月前，新浪再一次收紧了登录验证，除了邮箱其他所有可以登录微博的入口都加了二次验证，短信或者扫码或者私信，邮箱目前还是可以直接登录的，不知道什么时候也会被禁掉吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月27日(星期四) 凌晨4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaoqiangjun/gugubot] 几个使用问题 (#1)





 
感谢大佬回复！
 ***@***.******@***.******@***.******@***.******@***.***在邮箱界面登录是进不去邮箱的，直接跳转到微博，如此即便手机邮箱不能正常使用（或者实际上没注册上），也可以达到登录微博的目的？好吧。
 2.重复登录直到无需扫码登录，这句还是不太明白，我每次登录遇到的是要我输入手机验证码，扫码登录并不是必选项，不知是写错了还是

**Comment by In2013** [comment]
试了十多次还是....可能加V号安全策略不同吧，没辙了

**Comment by xiaoqiangjun** [comment]
emmm,每次都需要二次验证吗？或者你看下你手机微博是否主动开启了双重登录验证



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月27日(星期四) 下午4:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaoqiangjun/gugubot] 几个使用问题 (#1)





 
试了十多次还是....可能加V号安全策略不同吧，没辙了

**Comment by In2013** [comment]
没有开启/(ㄒoㄒ)/~~

**Comment by xiaoqiangjun** [comment]
那我也没得办法了，如果邮箱登录都不行的话，微博那里更不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月27日(星期四) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaoqiangjun/gugubot] 几个使用问题 (#1)





 
没有开启/(ㄒoㄒ)/~~

**Comment by In2013** [comment]
保存cookie到文件`COOKIES-MTU1NTU1`后，文件内容是什么样的呢？想要手填cookie，但这个文件乱码了

`Äcrequests.sessions Session q)Åq}q(Xheadersqcrequests.structures CaseInsensitiveDict q)Åq`

**Comment by xiaoqiangjun** [comment]
这里的cookies是我偷懒直接`pickle.dump`登录session的，并不是单独的cookies。如果你想手动输入cookies登录，相关的函数在`login.py`中，一个关键的函数是sess_update，你可以尝试修改下main中的流程。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月27日(星期四) 晚上6:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaoqiangjun/gugubot] 几个使用问题 (#1)





 
保存cookie到文件COOKIES-MTU1NTU1后，文件内容是什么样的呢？想要手填cookie，但这个文件乱码了
 
Ä�crequests.sessions Session q)Åq�}q�(X�headersq�crequests.structures CaseInsensitiveDict q�)Åq
